export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const REGISTER_NEW_USER_SUCCESS = "REGISTER_NEW_USER_SUCCESS";
export const REGISTER_NEW_USER_ERROR = "REGISTER_NEW_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const SET_USER = "SET_USER";
export const SET_IS_USER_LOGGED_IN_STATUS = "SET_IS_USER_LOGGED_IN_STATUS";
