export const ADD_NEW_TODO_ITEM = "ADD_NEW_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVED_TODO_ITEM";
export const COMPLETE_TODO_ITEM = "COMPLETE_TODO_ITEM";
export const EDIT_TODO_ITEM = "EDIT_TODO_ITEM";
export const CHANGE_CURRENT_TODOS_STATUS = "CHANGE_CURRENT_TODOS_STATUS";
