export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const FETCH_COUNTRY_DETAILS = "FETCH_COUNTRY_DETAILS";
export const MANAGE_FAVORITES = "MANAGE_FAVORITES";
